CREATE DATABASE IF NOT EXISTS task;
USE task;


DROP TABLE IF EXISTS `user`;
CREATE TABLE IF NOT EXISTS `user` (

  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL, 
  `username` VARCHAR(50) NULL DEFAULT NULL,
  `password` VARCHAR(30) NOT NULL,
  `imagepath` VARCHAR(100) NULL DEFAULT NULL,
  `aboutme` TEXT NULL DEFAULT NULL
  );

